baseurl         = "/"
theme           = "casper-two"
languageCode    = "zh-CN"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Same like,Same guy"
  subtitle    = "explain translate code  er"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "js/py/go tips"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = "chinanf-boy"

  logo = "hugo-logo.png"
  orgName = "yobrave"
  orgWebsite = "https://www.llever.com"
  orgDescription = "Here is a description placeholder for your org"


  author = "yobrave"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "GuangZhou"
  authorWebsite = "https://chinanf-boy.github.io"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "go"
  url = "/tags/golang"
  weight = 100

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "Projects"
  url = "/categories/pro/"
  weight = 95